Alive/Alive/Models/PayCategory.cs
using System.ComponentModel.DataAnnotations;
using System.Data.SqlTypes;

namespace Alive.Models
{
    public class PayCategory
    {
        [Key]
        public int? Id { get; set; }
        public string? Name { get; set; }
        public int? Unit { get; set; }
        public string? Description { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? Amountpaid { get; set; }


    }
}

Alive/Alive/Controllers/FinanceController.cs
using Alive.data;
using Alive.Models;
using Microsoft.AspNetCore.Mvc;

namespace Alive.Controllers
{
    public class FinanceController : Controller
    {
        private readonly AppDbContext _db;


        public FinanceController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Payment(Guid Id)
        {
            var signs = _db.Payments.Where(x => x.Id != Id).ToList();
            return View(signs);
        }

        //get - Create
        public IActionResult PaymentCreate()
        {

            return View();
        }
        //Post - Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PaymentCreate(Payment obj)
        {
            if (ModelState.IsValid)
            {
                _db.Payments.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Payment");
            }
            return View(obj);
        }
        //get - Edit
        [HttpGet]
        public IActionResult PaymentEdit(Guid Id)
        {
            if (Id == Guid.Empty)
            {
                return NotFound();
            }
            var obj = _db.Payments.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //Post -Edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PaymentEdit(Payment obj)
        {
            if (ModelState.IsValid)
            {
                _db.Payments.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Payment");
            }
            return View(obj);
        }
        //get - Delete
        public IActionResult PaymentDelete(Guid Id)
        {
            if (Id == null || Id == Guid.Empty)
            {
                return NotFound();
            }
            var obj = _db.Payments.Find(Id);
            if (obj == null)
            {
                return NotFound(obj);
            }

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PaymentDelete(Guid? Id)
        {
            var obj = _db.DocInfos.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.DocInfos.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("DocInfo");
            }
            return View(obj);
        }

        //public IActionResult Expenses()
        //{
        //    var signs = _db.Expenses.Where(x => x.Id != 0).ToList();
        //    return View(signs);
        //}

        ////get - Create
        //public IActionResult ExpensesCreate()
        //{

        //    return View();
        //}
        ////Post - Create

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult ExpensesCreate(Expenses obj)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _db.Expenses.Add(obj);
        //        _db.SaveChanges();
        //        return RedirectToAction("Expenses");
        //    }
        //    return View(obj);
        //}
        ////get - Edit
        //[HttpGet]
        //public IActionResult ExpensesEdit(int Id)
        //{
        //    if (Id == 0)
        //    {
        //        return NotFound();
        //    }
        //    var obj = _db.Expenses.Find(Id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(obj);
        //}
        ////Post -Edit

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult ExpensesEdit(Expenses obj)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _db.Expenses.Update(obj);
        //        _db.SaveChanges();
        //        return RedirectToAction("Expenses");
        //    }
        //    return View(obj);
        //}
        ////get - Delete
        //public IActionResult ExpensesDelete(int Id)
        //{
        //    if (Id == null || Id == 0)
        //    {
        //        return NotFound();
        //    }
        //    var obj = _db.Expenses.Find(Id);
        //    if (obj == null)
        //    {
        //        return NotFound(obj);
        //    }

        //    return View();
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult ExpensesDelete(int? Id)
        //{
        //    var obj = _db.Checkups.Find(Id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        _db.Checkups.Remove(obj);
        //        _db.SaveChanges();
        //        return RedirectToAction("Checkup");
        //    }
        //    return View(obj);
        //}
        //public IActionResult Debt()
        //{
        //    return View();
        //}
        public IActionResult PayCategory()
        {
            var signs = _db.PayCategories.Where(x => x.Id != 0).ToList();
            return View(signs);
        }

        //get - Create
        public IActionResult PayCategoryCreate()
        {

            return View();
        }
        //Post - Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PayCategoryCreate(PayCategory obj)
        {
            if (ModelState.IsValid)
            {
                _db.PayCategories.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("PayCategory");
            }
            return View(obj);
        }
        //get - Edit
        [HttpGet]
        public IActionResult PayCategoryEdit(int Id)
        {
            if (Id == 0)
            {
                return NotFound();
            }
            var obj = _db.PayCategories.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //Post -Edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PayCategoryEdit(PayCategory obj)
        {
            if (ModelState.IsValid)
            {
                _db.PayCategories.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("PayCategory");
            }
            return View(obj);
        }
        //get - Delete
        public IActionResult PayCategoryDelete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.PayCategories.Find(Id);
            if (obj == null)
            {
                return NotFound(obj);
            }

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PayCategoryDelete(int Id)
        {
            var obj = _db.PayCategories.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.PayCategories.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("paycategories");
            }
            return View(obj);
        }


        //public IActionResult ExpenseCategory()
        //{
        //    var signs = _db.ExpensesCategories.Where(x => x.Id != 0).ToList();
        //    return View(signs);
        //}

        ////get - Create
        //public IActionResult ExpensesCategoryCreate()
        //{

        //    return View();
        //}
        ////Post - Create

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult ExpensesCategoryCreate(ExpensesCategory obj)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _db.ExpensesCategories.Add(obj);
        //        _db.SaveChanges();
        //        return RedirectToAction("ExpensesCategory");
        //    }
        //    return View(obj);
        //}
        ////get - Edit
        //[HttpGet]
        //public IActionResult ExpensesCategoryEdit(int Id)
        //{
        //    if (Id == null)
        //    {
        //        return NotFound();
        //    }
        //    var obj = _db.ExpensesCategories.Find(Id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(obj);
        //}
        ////Post -Edit

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult ExpensesCategoryEdit(ExpensesCategory obj)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _db.ExpensesCategories.Update(obj);
        //        _db.SaveChanges();
        //        return RedirectToAction("ExpensesCategory");
        //    }
        //    return View(obj);
        //}
        ////get - Delete
        //public IActionResult ExpensesCategoryDelete(int? Id)
        //{
        //    if (Id == null || Id == 0)
        //    {
        //        return NotFound();
        //    }
        //    var obj = _db.ExpensesCategories.Find(Id);
        //    if (obj == null)
        //    {
        //        return NotFound(obj);
        //    }

        //    return View();
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult ExpensesCategoryDelete(int Id)
        //{
        //    var obj = _db.ExpensesCategories.Find(Id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        _db.ExpensesCategories.Remove(obj);
        //        _db.SaveChanges();

Alive/Alive/Views/Finance/Debt.cshtml
@{
    ViewData["Title"] = "Debt";
}

<h1>Debt</h1>

Alive/Alive/Views/Finance/PayCategory.cshtml
@{
    ViewData["Title"] = "PayCategory";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";

}
@model IEnumerable<Alive.Models.PayCategory>
<main id="main" class="main ">


    <section class="section">
        <div class="row">
            <div class="col-4">
                <a asp-controller="Finance" asp-action="PayCategoryCreate" method="post" class="btn btn-primary">

                    Add Patient Appointment
                </a>
            </div>


            <div class="col-4">
                <h2 class="" style="display:flex; text-align:center;justify-contentcenter;">Expenses List</h2>
            </div>

        </div>
        <div class="row align-items-top">

            <form class="search-form d-flex align-items-center" method="POST" action="#" style="float:right; display:flex; justify-content:end;">

                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>


        </div>
    </section>

    <!-- Default Card -->
    <section>
        <div class="card" style="width:100%">
            <div class="card-body">
                @if (Model.Count() > 0)
                {



                    <table class="table table-bordered border-primary">
                        <thead class="bg-danger">
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Description</th>
                                <th scope="col">Created Date</th>
                                <th scope="col"> </th>
                                <th scope="col"> </th>


                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var obj in Model)
                            {


                                <tr>
                                    <td>@obj.Name </td>
                                    <td>>@obj.Description</td>

                                    <td>>@obj.CreatedDate</td>
                                    <td><button type="button" asp-controller="Finance" asp-action="PayCategoryCreate" class="btn btn-primary">Edit</button></td>
                                    <td><button type="button" asp-controller="Finance" asp-action="PayCategoryDelete" class="btn btn-danger">Delete</button></td>



                                </tr>
                            }
                        </tbody>
                    </table>
                }
                <!-- End Primary Color Bordered Table -->

            </div>
        </div>




    </section>
</main><!-- End Default Card -->

Alive/Alive/Views/Finance/PayCategoryCreate.cshtml
@{
    ViewData["Title"] = "ExpensesCategoryCreate";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";

}
@model Alive.Models.PayCategory

<main id="main" class="main">





    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">

                        <!-- Default Tabs -->

                        <h5 class="card-title"></h5>
                        <div class="">
                            <!-- General Form Elements -->
                            <form asp-controller="Finance" asp-action="PayCategoryCreate" method="post">

                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>


                                <div class="row mb-3">
                                    <label for="Patientname" class="col-sm-5 col-form-label">Name</label>
                                    <div class="col-sm-7">
                                        <input type="text" asp-for="Name" id="amount" class="form-control">
                                        <span asp-validation-for="Name" class="text-danger"></span>

                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="type" class="col-sm-5 col-form-label">Description</label>
                                    <div class="col-sm-7">

                                        <input type="text" asp-for="Description" id="expenses" class="form-control">

                                        <span asp-validation-for="Description" class="text-danger"></span>

                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="DocName" class="col-sm-5 col-form-label">Date Created</label>
                                    <div class="col-sm-7">
                                        <input type="text" asp-for="CreatedDate" id="createddate" class="form-control">
                                        <span asp-validation-for="CreatedDate" class="text-danger"></span>

                                    </div>
                                </div>





                                <div class="row mb-3">
                                    <div class="form-group row ">
                                        <div class="col-8 offset-4 row">
                                            <div class="col mt-3 pt-3">
                                                <input type="submit" class=" btn btn-info w-100" value="Create" />

                                            </div>

                                            <div class="col mt-3 pt-3">
                                                <a asp-action="PayCategory" class="btn btn-success w-30">
                                                    <i class="fas fa-sign-out-alt"></i> Back
                                                </a>

                                            </div>

                                        </div>
                                    </div>

                                </div>




                            </form><!-- End General Form Elements -->

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

</main>

Alive/Alive/Views/Finance/PayCategoryDelete.cshtml
@{
    ViewData["Title"] = "PayCategoryDelete";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";

}
@model Alive.Models.PayCategory

<main id="main" class="main">





    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">

                        <!-- Default Tabs -->

                        <h5 class="card-title"></h5>
                        <div class="">
                            <!-- General Form Elements -->
                            <form asp-controller="Finance" asp-action="PayCategoryDelete" method="post">

                                <input asp-for="Id" hidden>


                                <div class="row mb-3">
                                    <label for="Patientname" class="col-sm-5 col-form-label">Name</label>
                                    <div class="col-sm-7">
                                        <input type="text" asp-for="Name" id="amount" class="form-control">
                                        <span asp-validation-for="Name" class="text-danger"></span>

                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="type" class="col-sm-5 col-form-label">Description</label>
                                    <div class="col-sm-7">

                                        <input type="text" asp-for="Description" id="expenses" class="form-control">

                                        <span asp-validation-for="Description" class="text-danger"></span>

                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="DocName" class="col-sm-5 col-form-label">Date Created</label>
                                    <div class="col-sm-7">
                                        <input type="text" asp-for="CreatedDate" id="createddate" class="form-control">
                                        <span asp-validation-for="CreatedDate" class="text-danger"></span>

                                    </div>
                                </div>





                                <div class="row mb-3">
                                    <div class="form-group row ">
                                        <div class="col-8 offset-4 row">
                                            <div class="col mt-3 pt-3">
                                                <input type="submit" class=" btn btn-info w-100" value="Delete" />

                                            </div>

                                            <div class="col mt-3 pt-3">
                                                <a asp-action="PayCategory" class="btn btn-success w-30">
                                                    <i class="fas fa-sign-out-alt"></i> Back
                                                </a>

                                            </div>

                                        </div>
                                    </div>

                                </div>




                            </form><!-- End General Form Elements -->

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

</main>

Alive/Alive/Views/Finance/PayCategoryEdit.cshtml
@{
    ViewData["Title"] = "PayCategoryEdit";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";

}
@model Alive.Models.PayCategory

<main id="main" class="main">





    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">

                        <!-- Default Tabs -->

                        <h5 class="card-title"></h5>
                        <div class="">
                            <!-- General Form Elements -->
                            <form asp-controller="Finance" asp-action="PayCategoryEdit" method="post">

                                <input asp-for="Id" hidden />


                                <div class="row mb-3">
                                    <label for="Patientname" class="col-sm-5 col-form-label">Name</label>
                                    <div class="col-sm-7">
                                        <input type="text" asp-for="Name" id="amount" class="form-control">
                                        <span asp-validation-for="Name" class="text-danger"></span>

                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="type" class="col-sm-5 col-form-label">Description</label>
                                    <div class="col-sm-7">

                                        <input type="text" asp-for="Description" id="expenses" class="form-control">

                                        <span asp-validation-for="Description" class="text-danger"></span>

                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="DocName" class="col-sm-5 col-form-label">Date Created</label>
                                    <div class="col-sm-7">
                                        <input type="text" asp-for="CreatedDate" id="createddate" class="form-control">
                                        <span asp-validation-for="CreatedDate" class="text-danger"></span>

                                    </div>
                                </div>





                                <div class="row mb-3">
                                    <div class="form-group row ">
                                        <div class="col-8 offset-4 row">
                                            <div class="col mt-3 pt-3">
                                                <input type="submit" class=" btn btn-info w-100" value="Create" />

                                            </div>

                                            <div class="col mt-3 pt-3">
                                                <a asp-action="PayCategory" class="btn btn-success w-30">
                                                    <i class="fas fa-sign-out-alt"></i> Back
                                                </a>

                                            </div>

                                        </div>
                                    </div>

                                </div>




                            </form><!-- End General Form Elements -->

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

</main>