Alive/Alive/Models/NurseViewModel.cs
namespace Alive.Models
{
    public class NurseViewModel
    {
        public List<NurseInfo>? Nurseinfos { get; set; }
        public NurseInfo? NurseInfo { get; set; }

    }
}

Alive/Alive/Controllers/NurseController.cs
using Alive.data;
using Alive.Models;
using Microsoft.AspNetCore.Mvc;

namespace Alive.Controllers
{
    public class NurseController : Controller
    {
        private readonly AppDbContext _db;


        public NurseController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Nvitalsign()
        {
            var signs = _db.VitalSigns.Where(x => x.Id != 0).ToList();
            return View(signs);
        }

        //get - Create
        public IActionResult VitalCreate()
        {

            return View();
        }
        //Post - Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult VitalCreate(VitalSign obj)
        {
            if (ModelState.IsValid)
            {
                _db.VitalSigns.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Nvitalsign");
            }
            return View(obj);
        }
        //get - Edit
        [HttpGet]
        public IActionResult VitalEdit(int Id)
        {
            if (Id == 0)
            {
                return NotFound();
            }
            var obj = _db.VitalSigns.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //Post -Edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult VitalEdit(VitalSign obj)
        {
            if (ModelState.IsValid)
            {
                _db.VitalSigns.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Nvitalsign");
            }
            return View(obj);
        }
        //get - Delete
        public IActionResult Delete(int Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.VitalSigns.Find(Id);
            if (obj == null)
            {
                return NotFound(obj);
            }

            return View();
        }
        public IActionResult Appointment()
        {
            return View();
        }
        public IActionResult Checkup()
        {
            return View();
        }
        public IActionResult Patient()
        {
            return View();
        }
        public IActionResult Bed()
        {
            return View();
        }
        public IActionResult Bedcategory()
        {
            return View();
        }
        public IActionResult BedAllotment()
        {
            return View();
        }
        public IActionResult Info()
        { 
            return View();  
        }
    }
}

Alive/Alive/Views/Nurse/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NurseLayout.cshtml";

}

<main id="main" class="main ">

    <div class="pagetitle mt-2">
        <h1>Dashboard</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-action="Home" asp-controller="Home"></a>Home</li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row align-items-top">
            <div class="col-lg-3 ">

                <!-- Default Card -->
                <div class="card">
                    <div class="card-body">
                        <div class="row mt-3">
                            <div class="col-4 ">
                                <a href="components-accordion.html">
                                    <img src="~/niceadmin/assets/img/apple-touch-icon.png" style="width:70%; height:70%;" />
                                </a>
                            </div>
                            <div class="col-4">
                                <h6 class="" style="color:darkblue; font-size:medium;">Patients</h6>

                            </div>
                            <div class="col-4">
                                <h6 class="" id="num" style="color:darkred; font-size:large;">6</h6>

                            </div>


                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">

                <!-- Default Card -->
                <div class="card">
                    <div class="card-body">
                        <div class="row mt-3">
                            <div class="col-4 ">
                                <a href="components-accordion.html">
                                    <img src="~/niceadmin/assets/img/apple-touch-icon.png" style="width:70%; height:70%;" />
                                </a>
                            </div>
                            <div class="col-4">
                                <h6 class="" style="color:darkblue; font-size:medium;">Doctors</h6>

                            </div>
                            <div class="col-4">
                                <h6 class="" id="num" style="color:darkred; font-size:large;">6</h6>

                            </div>


                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">

                <!-- Default Card -->
                <div class="card">
                    <div class="card-body">
                        <div class="row mt-3">
                            <div class="col-4 ">
                                <a href="components-accordion.html">
                                    <img src="~/niceadmin/assets/img/apple-touch-icon.png" style="width:70%; height:70%;" />
                                </a>
                            </div>
                            <div class="col-4">
                                <h6 class="" style="color:darkblue; font-size:medium;">Nurses</h6>

                            </div>
                            <div class="col-4">
                                <h6 class="" id="num" style="color:darkred; font-size:large;">6</h6>

                            </div>


                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">

                <!-- Default Card -->
                <div class="card">
                    <div class="card-body">
                        <div class="row mt-3">
                            <div class="col-4 ">
                                <a href="components-accordion.html">
                                    <img src="~/niceadmin/assets/img/apple-touch-icon.png" style="width:70%; height:70%;" />
                                </a>
                            </div>
                            <div class="col-4">
                                <h6 class="" style="color:darkblue; font-size:medium;">Laboratory</h6>

                            </div>
                            <div class="col-4">
                                <h6 class="" id="num" style="color:darkred; font-size:large;">6</h6>

                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row align-items-top">
            <div class="col-lg-3">

                <!-- Default Card -->
                <div class="card">
                    <div class="card-body">
                        <div class="row mt-3">
                            <div class="col-4 ">
                                <a href="components-accordion.html">
                                    <img src="~/niceadmin/assets/img/apple-touch-icon.png" style="width:70%; height:70%;" />
                                </a>
                            </div>
                            <div class="col-4">
                                <h6 class="" style="color:darkblue; font-size:medium;">Pharmacy</h6>

                            </div>
                            <div class="col-4">
                                <h6 class="" id="num" style="color:darkred; font-size:large;">6</h6>

                            </div>


                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">

                <!-- Default Card -->
                <div class="card">
                    <div class="card-body">
                        <div class="row mt-3">
                            <div class="col-4 ">
                                <a href="components-accordion.html">
                                    <img src="~/niceadmin/assets/img/apple-touch-icon.png" style="width:70%; height:70%;" />
                                </a>
                            </div>
                            <div class="col-4">
                                <h6 class="" style="color:darkblue; font-size:medium;">Medicine</h6>

                            </div>
                            <div class="col-4">
                                <h6 class="" id="num" style="color:darkred; font-size:large;">6</h6>

                            </div>


                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">

                <!-- Default Card -->
                <div class="card">
                    <div class="card-body">
                        <div class="row mt-3">
                            <div class="col-4 ">
                                <a href="components-accordion.html">
                                    <img src="~/niceadmin/assets/img/apple-touch-icon.png" style="width:70%; height:70%;" />
                                </a>
                            </div>
                            <div class="col-4">
                                <h6 class="" style="color:darkblue; font-size:medium;">Bed</h6>

                            </div>
                            <div class="col-4">
                                <h6 class="" id="num" style="color:greenyellow; font-size:large;">6</h6>

                            </div>


                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">

                <!-- Default Card -->
                <div class="card">
                    <div class="card-body">
                        <div class="row mt-3">
                            <div class="col-4 ">
                                <a href="components-accordion.html">
                                    <img src="~/niceadmin/assets/img/apple-touch-icon.png" style="width:70%; height:70%;" />
                                </a>
                            </div>
                            <div class="col-4">
                                <h6 class="" style="color:darkblue; font-size:medium;">Account</h6>

                            </div>
                            <div class="col-4">
                                <h6 class="" id="num" style="color:greenyellow; font-size:large;">6</h6>

                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>      <!-- End Default Card -->

    <section class="section">
        <div class="row align-items-top">


            <!-- Default Card -->
            <div class="card" style="width:100%">
                <div class="card-body">
                    <h5 class="card-title">Recent Payment</h5>

                    <table class="table table-bordered border-primary">
                        <thead class="bg-danger">
                            <tr>
                                <th scope="col">id</th>
                                <th scope="col">Name</th>
                                <th scope="col">Sub</th>
                                <th scope="col">Grand total</th>
                                <th scope="col">Created date</th>
                                <th scope="col"></th>

                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td>Brandon Jacob</td>
                                <td>Designer</td>
                                <td>28</td>
                                <td>2016-05-25</td>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>Bridie Kessler</td>
                                <td>Developer</td>
                                <td>35</td>
                                <td>2014-12-05</td>
                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Ashleigh Langosh</td>
                                <td>Finance</td>
                                <td>45</td>
                                <td>2011-08-12</td>
                            </tr>
                            <tr>
                                <th scope="row">4</th>
                                <td>Angus Grady</td>
                                <td>HR</td>
                                <td>34</td>
                                <td>2012-06-11</td>
                            </tr>
                            <tr>
                                <th scope="row">5</th>
                                <td>Raheem Lehner</td>
                                <td>Dynamic Division Officer</td>
                                <td>47</td>
                                <td>2011-04-19</td>
                            </tr>
                            <tr>
                                <th scope="row">5</th>
                                <td>Raheem Lehner</td>
                                <td>Dynamic Division Officer</td>
                                <td>47</td>
                                <td>2011-04-19</td>
                            </tr>
                        </tbody>
                    </table>
                    <!-- End Primary Color Bordered Table -->

                </div>
            </div>

        </div>


    </section><!-- End Default Card -->







</main><!-- End #main -->

Alive/Alive/Views/Nurse/Info.cshtml
@{
    ViewData["Title"] = "Info";
}

<h1>Info</h1>

Alive/Alive/Views/Nurse/NAppointment.cshtml
@{
    ViewData["Title"] = "NAppointment";
}

<h1>NAppointment</h1>

Alive/Alive/Views/Nurse/NBed.cshtml
@{
    ViewData["Title"] = "NBed";
}

<h1>NBed</h1>

Alive/Alive/Views/Nurse/NBedAllotment.cshtml
@{
    ViewData["Title"] = "NBedAllotment";
}

<h1>NBedAllotment</h1>

Alive/Alive/Views/Nurse/NBedcategory.cshtml
@{
    ViewData["Title"] = "NBedcategory";
}

<h1>NBedcategory</h1>

Alive/Alive/Views/Nurse/NPatient.cshtml
@{
    ViewData["Title"] = "NPatient";
}

<h1>NPatient</h1>

Alive/Alive/Views/Nurse/Nvitalsign.cshtml
@{
    ViewData["Title"] = "vitalsign";
    Layout = "~/Views/Shared/_NurseLayout.cshtml";

}
@model IEnumerable<Alive.Models.VitalSign>

<main id="main" class="main ">


    <section class="section">
        <div class="row">
            <div class="col-4">
                <a asp-controller="Nurse" asp-action="VitalCreate" method="post" class="btn btn-primary">

                    Add Vital sign Modal
                </a>
            </div>
            <div class="col-4">
                <h2 class="" style="display:flex; text-align:center;justify-content:center;">Patients Vital Sign</h2>
            </div>

        </div>





        <div class="row align-items-top">

            <form class="search-form d-flex align-items-center" method="POST" action="#" style="float:right; display:flex; justify-content:end;">

                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>


        </div>

    </section>

    <!-- Default Card -->
    <section>
        <div class="card" style="width:100%">
            <div class="card-body">
                <h5 class="card-title"></h5>

                @*@if (Model?.VitalSignTables != null &&  Model?.VitalSignTables.Count()>0)
                *@
                @if (Model.Count() > 0)
                {
                    <table class="table table-bordered border-primary">
                        <thead class="bg-danger">
                            <tr>

                                <th scope="col">Visit id</th>

                                <th scope="col">Patient Name</th>
                                <th scope="col">Nurse Name</th>
                                <th scope="col">BP</th>
                                <th scope="col">Pulse Rate</th>
                                <th scope="col">Body Temperature </th>
                                <th scope="col">Body Weight </th>
                                <th scope="col">Body Height </th>
                                <th scope="col">Comment </th>
                                <th scope="col">Action </th>


                            </tr>
                        </thead>
                        <tbody>
                            @*@foreach (var obj in Model.VitalSignTables)
                        *@
                            @foreach (var obj in Model)
                            {

                                <tr>
                                    <td>@obj.VisitId</td>
                                    <td>@obj.Name</td>
                                    <td>@obj.NurseName</td>
                                    <td>@obj.BloodPressure</td>
                                    <td>@obj.PulseRate</td>
                                    <td>@obj.BodyTemperature</td>
                                    <td>@obj.BodyWeight</td>
                                    <td>@obj.Height</td>
                                    <td>@obj.Comment</td>


                                    <td>
                                        <a asp-controller="Nurse" asp-route-id="@obj.Id" asp-action="NvitalEdit" class="btn btn-danger">
                                            Edit
                                        </a>
                                    </td>



                                </tr>
                            }

                        </tbody>
                    </table>
                }
                else
                {
                    <p>No Category exists.</p>
                }
                <!-- End Primary Color Bordered Table -->

            </div>
        </div>





        <!-- End Basic Modal-->



    </section>



</main><!-- End Default Card -->

Alive/Alive/Views/Nurse/VitalCreate.cshtml
@{
    ViewData["Title"] = "VitalCreate";
    Layout = "~/Views/Shared/_NurseLayout.cshtml";

}

@model Alive.Models.VitalSign
<main id="main" class="main">



    <section class="section">
        <div class="row">
            <div class="col-lg-6">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">General Form Elements</h5>

                        <!-- General Form Elements -->
                        <form asp-controller="admin" asp-action="VitalCreate" method="post">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="row mb-3">
                                <label for="PatientName" class="col-sm-5 col-form-label">Patient Name</label>
                                <div class="col-sm-7">
                                    <input type="text" id="name" asp-for="Name" class="form-control">
                                    <span asp-validation-for="Name" class="text-danger"></span>

                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="VisitId" class="col-sm-5 col-form-label">Visit id</label>
                                <div class="col-sm-7">
                                    <span asp-validation-for="Id" class="text-danger"></span>

                                    <input type="text" id="vId" asp-for="VisitId" class="form-control" />

                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class=" col-form-label col-sm-5">Attended by Nurse</label>

                                <div class="input-group mb-3 col-sm-7">
                                    <input type="text" id="nurseName" asp-for="NurseName" class="form-control input-group-text" />
                                    <span asp-validation-for="NurseName" class="text-danger"></span>
                                </div>

                            </div>

                            <div class="row mb-3">

                                <label class=" col-form-label col-sm-5">Body Temperature</label>
                                <div class="">
                                    <div class="input-group mb-3 col-sm-7">
                                        <input type="text" id="temperature" asp-for="BodyTemperature" class="form-control input-group-text" aria-describedby="basic-addon1">
                                        <span asp-validation-for="BodyTemperature" class="text-danger">C</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class=" col-form-label col-sm-5">Body Height</label>

                                <div class="input-group mb-3 col-sm-7 ">
                                    <input type="text" id="height" asp-for="Height" class="form-control input-group-text" aria-describedby="basic-addon1">
                                    <span asp-validation-for="Height" class="text-danger">CM</span>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label class="col-form-label col-sm-5">Body Weight</label>

                                <div class="input-group mb-3 col-sm-7">
                                    <input type="text" id="weight" asp-for="BodyWeight" class="form-control input-group-text" aria-describedby="basic-addon1">
                                    <span asp-validation-for="BodyWeight" class="text-danger">KG</span>
                                </div>

                            </div>
                            <div class="row mb-3">
                                <label class=" col-form-label">BMI</label>

                                <input type="number" class="form-control" id="bodyIndex" aria-describedby="basic-addon1" />
                                <select class="form-select" id="bmi" aria-label="Floating label select example">
                                    <option selected></option>
                                    <option value="1">  Overweight</option>
                                    <option value="2">Normal</option>
                                    <option value="3">Underweight</option>
                                </select>


                            </div>

                            <div class="row mb-3">
                                <label class=" col-form-label col-sm-5">Respiration Rate</label>

                                <div class="input-group mb-3 col-sm-7">
                                    <input type="text" id="pulse" asp-for="PulseRate" class="form-control input-group-text" aria-describedby="basic-addon1">
                                    <span asp-validation-for="PulseRate" class="text-danger">PER SECs</span>
                                </div>

                            </div>
                            <div class="row mb-3 col-sm-5">
                                <label class=" col-form-label">Blood Pressure</label>

                                <div class="input-group mb-3 col-sm-7">
                                    <input type="text" id="pressure" asp-for="BloodPressure" class="form-control input-group-text" aria-describedby="basic-addon1">
                                    <span asp-validation-for="BloodPressure" class="text-danger">MM/HG</span>
                                </div>

                            </div>
                            <div class="row form-floating mb-3">
                                <label for="floatingTextarea">Patient's Complaints</label>

                                <textarea class="form-control" placeholder="Leave a comment here" id="Complain" asp-for="Comment" style="height: 100px;"></textarea>
                                <span asp-validation-for="Comment" class="text-danger"></span>

                            </div>
                            <div class="row mb-3">
                                <div class="form-group row ">
                                    <div class="col-8 offset-4 row">
                                        <div class="col mt-3 pt-3">
                                            <input type="submit" class=" btn btn-info w-100" value="Create" />

                                        </div>

                                        <div class="col mt-3 pt-3">
                                            <a asp-action="VitalCreate" class="btn btn-success w-30">
                                                <i class="fas fa-sign-out-alt"></i> Back
                                            </a>

                                        </div>

                                    </div>
                                </div>

                            </div>


                        </form><!-- End General Form Elements -->

                    </div>
                </div>

            </div>
        </div>
    </section>
</main>